theme = "monokai_pro"

[editor]
line-number = "relative"
cursorline = true
auto-format = false
color-modes = true
auto-info = true
auto-completion = true
auto-pairs = false

[editor.lsp]
display-messages = true
auto-signature-help	= false
display-signature-help-docs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true

[editor.whitespace.render]
newline = "all"
[editor.file-picker]
hidden = true

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
"C-s" = ":wa"

l = "goto_first_nonwhitespace"
y = "goto_line_end_newline"
L = ["split_selection_on_newline", "insert_at_line_start"]
Y = ["split_selection_on_newline", "insert_at_line_end"]
u = "move_line_up"
e = "move_line_down"
n = "move_char_left"
i = "move_char_right"
N = "move_prev_word_start"
I = "move_next_word_end"

"C-u" = ["move_line_up", "move_line_up", "move_line_up", "move_line_up"]
"C-e" = ["move_line_down", "move_line_down", "move_line_down", "move_line_down"]
O = "search_prev"
o = "search_next"
"C-o" = "remove_primary_selection"
"?" = ["expand_selection", "search_selection", "search_next"]


"," = "repeat_last_motion"

";" = "flip_selections"      
"C-x" = "split_selection_on_newline"
"X" = "trim_selections"


B = "jump_forward"
b = "jump_backward"

"w" = "select_mode" # z (view mode) should be mapped to v
"h" = "insert_mode"
"H" = ["kill_to_line_start", "insert_mode"]
"ret" = "append_mode"
"S-ret" = ["kill_to_line_end", "insert_mode"]
"_" = "change_selection_noyank"
"minus" = "replace"

E = "copy_selection_on_next_line"
U = "copy_selection_on_prev_line"

z = "undo"
Z = "redo"
d = "delete_selection_noyank"
D = "delete_selection"
a = "expand_selection"
A = "shrink_selection"

"(" = "surround_add"
")" = "surround_delete"
"=" = "surround_replace"
m = "match_brackets"
M = "select_textobject_inner"

"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]

c = ["normal_mode", "yank"]
C = ["normal_mode", ":clipboard-yank"]
p = "paste_before"
P = ":clipboard-paste-before"
# P = "paste_after"
r = "replace_with_yanked"
R = ":clipboard-paste-replace"
# R = "replace_with_yanked"


j = "add_newline_above"
J = "open_above"
k = "add_newline_below"
K = "open_below"

# [keys.normal."@"]
# c = ["normal_mode", ":clipboard-yank"]
# d = "delete_selection"
# p = ":clipboard-paste-before"
# P = ":clipboard-paste-after"
# r = ":clipboard-paste-replace"

[keys.normal.s]
j = "join_selections_space"
s = "select_regex"
S = "split_selection"
k = "keep_selections"
x = "split_selection_on_newline"
t = "trim_selections"
d = "remove_primary_selection"
D = "remove_selections"
c = "save_selection"
m = "merge_consecutive_selections"
n = "rotate_selections_backward"
i = "rotate_selections_forward"
N = "rotate_selection_contents_backward"
I = "rotate_selection_contents_forward"

[keys.normal.W]
	I   = "vsplit"
	E   = "hsplit"
	q   = "wclose"
	k   = "wonly"
	i   = "jump_view_right" 
  e   = "jump_view_down"
	u   = "jump_view_up" 
	n   = "jump_view_left"
	w   = "rotate_view"

[keys.normal.v]
	v   = "align_view_center"
	u   = "align_view_top"
	e   = "align_view_bottom"
	U   = "scroll_up"
	E   = "scroll_down"


[keys.normal.g]
g = "goto_next_diag"
G = "goto_prev_diag"
u = "goto_window_top"
U = "goto_file_start"
e = "goto_window_bottom"
E = "goto_file_end"
i = "find_till_char"
o = "find_next_char"
n = "till_prev_char"
m = "find_prev_char"

[keys.normal.space]
R = ":sh kitty @ send-text --match 'num:0' 'clear\\ncargo run\\n'"
t = ":sh kitty @ send-text --match 'num:0' 'clear\\ncargo test\\n'"
T = ":pipe-to xargs -I {} kitty @ send-text --match 'num:0' 'clear\\ncargo test {}\\n'"

##########################################################################################
##########################################################################################
##########################################################################################
##########################################################################################
# SELECT
##########################################################################################
##########################################################################################
##########################################################################################
[keys.select]
w = "select_mode"
"C-s" = ["normal_mode", ":wa"]

"(" = "surround_add"
")" = "surround_delete"
"=" = "surround_replace"


E = "copy_selection_on_next_line"
U = "copy_selection_on_prev_line"


l = "goto_first_nonwhitespace"
y = "goto_line_end_newline"
L = ["split_selection_on_newline", "insert_at_line_start"]
Y = ["split_selection_on_newline", "insert_at_line_end"]
u = "extend_line_up"
e = "extend_line_down"
n = "extend_char_left"
i = "extend_char_right"
N = "extend_prev_word_start"
I = "extend_next_word_end"

"C-u" = ["extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up"]
"C-e" = ["extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down"]

m = "match_brackets"
M = "select_textobject_inner"

"," = "repeat_last_motion"

";" = "flip_selections"


B = "jump_forward"
b = "jump_backward"

"h" = "insert_mode"
"H" = "insert_at_line_start"
"ret" = "append_mode"
"S-ret" = "insert_at_line_end"
"_" = "change_selection_noyank"
"minus" = "replace"


c = ["normal_mode", "yank"]
C = ["normal_mode", ":clipboard-yank"]
p = "paste_before"
P = ":clipboard-paste-before"
# P = "paste_after"
r = "replace_with_yanked"
R = ":clipboard-paste-replace"
# R = "replace_with_yanked"

z = "undo"
Z = "redo"
d = "delete_selection_noyank"
D = "delete_selection"
a = "expand_selection"
A = "shrink_selection"

j = "add_newline_above"
J = "open_above"
k = "add_newline_below"
K = "open_below"
O = "extend_search_prev"
o = "extend_search_next"

"esc" = "normal_mode"

# [keys.select."@"]
# c = ["normal_mode", ":clipboard-yank"]
# d = "delete_selection"
# p = ":clipboard-paste-before"
# P = ":clipboard-paste-after"
# r = ":clipboard-paste-replace"

[keys.select.s]
j = "join_selections_space"
s = "select_regex"
S = "split_selection"
k = "keep_selections"
x = "split_selection_on_newline"
t = "trim_selections"
d = "remove_primary_selection"
D = "remove_selections"
c = "save_selection"
m = "merge_consecutive_selections"
n = "rotate_selections_backward"
i = "rotate_selections_forward"
N = "rotate_selection_contents_backward"
I = "rotate_selection_contents_forward"

[keys.select.g]
g = "goto_next_diag"
G = "goto_prev_diag"
u = "goto_window_top"
U = "goto_file_start"
e = "goto_window_bottom"
E = "goto_file_end"
i = "find_till_char"
o = "find_next_char"
n = "till_prev_char"
m = "find_prev_char"

[keys.select.v]
	v   = "align_view_center"
	u   = "align_view_top"
	e   = "align_view_bottom"
	U   = "scroll_up"
	E   = "scroll_down"

[keys.select.space]
R = ":sh kitty @ send-text --match 'num:0' 'clear\\ncargo run\\n'"
t = ":sh kitty @ send-text --match 'num:0' 'clear\\ncargo test\\n'"
T = ":pipe-to xargs -I {} kitty @ send-text --match 'num:0' 'clear\\ncargo test {}\\n'"

[keys.insert]
"C-s" = ["normal_mode", ":wa"]
"C-p" = "paste_before"
"C-P" = ":clipboard-paste-before"


