theme = "monokai_pro"

[editor]
line-number = "relative"
cursorline = true
auto-format = false
color-modes = true
auto-info = true
auto-completion = true

[editor.lsp]
display-messages = true
auto-signature-help	= false
display-signature-help-docs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true


[keys.normal]
"C-s" = ":wa"

l = "goto_line_start"
L = "kill_to_line_start"
y = "goto_line_end"
Y = "kill_to_line_end"
u = "move_line_up"
e = "move_line_down"
n = "move_char_left"
i = "move_char_right"
o = "move_next_word_start"
O = "move_next_word_end"
N = "move_prev_word_start"
#I = "move_next_word_end"

j = "search_prev"
k = "search_next"
"?" = ["expand_selection", "search_selection", "search_next"]

x = "copy_selection_on_next_line"
X = "copy_selection_on_prev_line"
#S = "select_regex"

"," = "repeat_last_motion"

";" = "flip_selections"


B = "jump_forward"
b = "jump_backward"

"w" = "select_mode" # z (view mode) should be mapped to v
"h" = "insert_mode"
"H" = "insert_at_line_start"
"tab" = "append_mode"
"S-tab" = "insert_at_line_end"
#"minus" = "insert_at_line_end"
"_" = "change_selection_noyank"
#"R" = "replace"
"ret" = "open_below"
"S-ret" = "open_above"

"p" = "paste_before"
"P" = ["select_register",  "paste_before"]
"C" = ["select_register",  "yank"]

#"C-r" = "replace_with_yanked"


#"ret" = "add_newline_below"
#"S-ret" = "add_newline_above"


c = "yank"
z = "undo"
Z = "redo"
d = "delete_selection_noyank"
D = "delete_selection"
a = "expand_selection"
A = ["extend_line_below", "select_mode"]

"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.W]
	I   = "vsplit"
	E   = "hsplit"
	"q"   = "wclose"
	"k"   = "wonly"
	"i"   = "jump_view_right" 
    "e"   = "jump_view_down"
	"u"   = "jump_view_up" 
	"n"   = "jump_view_left"
	"w"   = "rotate_view"
#sticky = true

[keys.select]
l = "extend_to_line_start"
y = "extend_to_line_end"
u = "extend_line_up"
e = "extend_line_down"
n = "extend_char_left"
i = "extend_char_right"
o = "extend_next_word_start"
O = "extend_next_word_end"
N = "extend_prev_word_start"
#I = "extend_next_word_end"

j = "extend_search_prev"
k = "extend_search_next"

x = "copy_selection_on_next_line"
X = "copy_selection_on_prev_line"
#S = "select_regex"

"," = "repeat_last_motion"

";" = "flip_selections"


B = "jump_forward"
b = "jump_backward"

"h" = "insert_mode"
"H" = "insert_at_line_start"
"_" = "append_mode"
"minus" = "insert_at_line_end"
"_" = "change_selection_noyank"
#"R" = "replace"
"ret" = "open_below"
"S-ret" = "open_above"

"p" = "paste_before"
"P" = "paste_after"
"C" = ["select_register",  "yank"]

#"C-r" = "replace_with_yanked"

#"ret" = "add_newline_below"
#"S-ret" = "add_newline_above"


c = "yank"
z = "undo"
Z = "redo"
d = "delete_selection_noyank"
D = "delete_selection"
a = "expand_selection"
A = "extend_line_below"

"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
