
theme = "monokai_pro"

[editor]
line-number = "relative"
cursorline = true
auto-format = false
color-modes = true
auto-info = true
auto-completion = true
auto-pairs = false

[editor.lsp]
display-messages = true
auto-signature-help	= false
display-signature-help-docs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true

[editor.whitespace.render]
newline = "all"
[editor.file-picker]
hidden = true

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
"C-s" = ":wa"

l = "goto_first_nonwhitespace"
y = "goto_line_end_newline"
L = ["split_selection_on_newline", "insert_at_line_start"]
Y = ["split_selection_on_newline", "insert_at_line_end"]
u = "move_line_up"
e = "move_line_down"
n = "move_char_left"
i = "move_char_right"
N = "move_prev_word_start"
I = "move_next_word_end"

j = "search_prev"
k = "search_next"
K = "remove_primary_selection"
"?" = ["expand_selection", "search_selection", "search_next"]


"," = "repeat_last_motion"

";" = "flip_selections"      
"C-x" = "split_selection_on_newline"
"X" = "trim_selections"


B = "jump_forward"
b = "jump_backward"

"w" = "select_mode" # z (view mode) should be mapped to v
"h" = "insert_mode"
"H" = ["kill_to_line_start", "insert_mode"]
"ret" = "append_mode"
"S-ret" = ["kill_to_line_end", "insert_mode"]
"_" = "change_selection_noyank"

E = "copy_selection_on_next_line"
U = "copy_selection_on_prev_line"


z = "undo"
Z = "redo"
d = "delete_selection_noyank"
D = "delete_selection"
a = "expand_selection"
A = "shrink_selection"
J = "join_selections_space"

"(" = "surround_add"
")" = "surround_delete"
"minus" = "surround_replace"
m = "select_textobject_inner"
M = "select_textobject_around"

"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]

c = ["normal_mode", "yank"]
C = ["normal_mode", ":clipboard-yank"]
p = "paste_before"
P = ":clipboard-paste-before"
R = "replace_with_yanked"

[keys.normal.W]
	I   = "vsplit"
	E   = "hsplit"
	q   = "wclose"
	k   = "wonly"
	i   = "jump_view_right" 
  e   = "jump_view_down"
	u   = "jump_view_up" 
	n   = "jump_view_left"
	w   = "rotate_view"

[keys.normal.v]
	v   = "align_view_center"
	u   = "scroll_up"
	e   = "scroll_down"
	U   = "align_view_top"
	E   = "align_view_bottom"


[keys.normal.g]

[keys.select]
w = "select_mode"
"C-s" = ["normal_mode", ":wa"]

"(" = "surround_add"
")" = "surround_delete"
"minus" = "surround_replace"



l = "goto_first_nonwhitespace"
y = "goto_line_end_newline"
L = ["split_selection_on_newline", "insert_at_line_start"]
Y = ["split_selection_on_newline", "insert_at_line_end"]
u = "extend_line_up"
e = "extend_line_down"
n = "extend_char_left"
i = "extend_char_right"
N = "extend_prev_word_start"
I = "extend_next_word_end"

j = "extend_search_prev"
k = "extend_search_next"
K = "remove_primary_selection"


"," = "repeat_last_motion"

";" = "flip_selections"


B = "jump_forward"
b = "jump_backward"

"h" = "insert_mode"
"H" = "insert_at_line_start"
"ret" = "append_mode"
"S-ret" = "insert_at_line_end"
"_" = "change_selection_noyank"

"X" = "trim_selections"


c = ["normal_mode", "yank"]
C = ["normal_mode", ":clipboard-yank"]
p = "paste_before"
P = ":clipboard-paste-before"
R = "replace_with_yanked"
z = "undo"
Z = "redo"
d = "delete_selection_noyank"
D = "delete_selection"
a = "expand_selection"
A = "shrink_selection"
J = "join_selections_space"

"esc" = "normal_mode"


[keys.insert]
"C-s" = ["normal_mode", ":wa"]
"C-p" = "paste_before"
"C-P" = ":clipboard-paste-before"
